services:
  - type: web
    name: web-portfolio
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --optimize-autoloader --no-dev --no-scripts
      npm install && npm run build
      composer run-script post-autoload-dump
      php artisan key:generate --no-interaction
      php artisan migrate --force --no-interaction
      php artisan db:seed --force --no-interaction
      php artisan config:cache --no-ansi
      php artisan route:cache --no-ansi
      php artisan view:cache --no-ansi
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: web-portfolio
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_LIFETIME
        value: 120
      - key: MAIL_MAILER
        value: log
      - key: ADMIN_EMAIL
        value: admin@yourportfolio.com
      - key: ADMIN_PASSWORD
        value: changeme123!
      - key: GOOGLE_ANALYTICS_ID
        value: G-L0RHNJ2SQB